sitio/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
	url(r'^votacion/', include('votacion.urls',namespace='votacion')),
	#url(r'^media/', include('votacion.urls',namespace='votacion')),
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^media/', include('votacion.urls',namespace='votacion')),
    url(r'^media/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.MEDIA_ROOT,}),
]

votacion/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(),  name='index'),
    url(r'^recomendar/$', views.nuevo_Recomendado, name='recomendar'),
    url(r'^recomendar/success$', views.recomendarSuccess, name='recomendarSuccess'),
    url(r'^calificar/$', views.nueva_Calificacion, name='calificar'),
    #login
    url(r'^login/$' ,views.LoginView.as_view(),name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
	# register
    url(r'^registrarme/$', views.RegistrarView.as_view(), name='registrarme'),
    url(r'^registrarme/success/$',views.RegistrarSuccessView.as_view(), name='registrarme-success'),
    #reportes
    url(r'^recientes/$', views.RecientesProfesoresView, name='recientes'),
    url(r'^populares/$', views.PopularesProfesoresView, name='populares'),
    url(r'^top/$', views.TopXProfesoresView, name='top'),
    url(r'^busca/$', views.BuscarProfesoresView, name='busca'),
]

votacion/models.py
import datetime
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from datetime import datetime  

class Universidad(models.Model):
    nombre = models.CharField(max_length=100)
    ciudad = models.CharField(max_length=50)
    provincia = models.CharField(max_length=50)
    logo = models.ImageField(upload_to="logos",blank=True)

    class Meta:
        ordering = ["nombre"]
        verbose_name_plural = "Universidades"

    def __str__(self):            
        return self.nombre

class Unidad(models.Model):
    nombre= models.CharField(max_length=50)
    universidad = models.ForeignKey(Universidad)

    class Meta:
        ordering = ["nombre"]
        verbose_name_plural = "Unidades"

    def __str__(self):   
        return self.nombre

class Profesor(models.Model):
    Estados=((1,'Confirmado'),(2,'No Confirmado'),(3,'Rechazado'))
    apellido = models.CharField(max_length=50,blank=False)
    nombre = models.CharField(max_length=50,blank=False)
    apodo = models.CharField(max_length=50,blank=True)
    foto = models.ImageField(upload_to="fotos",blank=True)
    linkedin = models.CharField(max_length=200, blank=True)
    confirmado_flag = models.IntegerField(choices=Estados,default=2)
    universidad = models.ForeignKey(Universidad,blank=False)
    unidad = models.ForeignKey(Unidad,blank=False)
    user = models.ForeignKey(User)
    
    class Meta:
        ordering = ["nombre"]
        verbose_name_plural = "Profesores"

    def __str__(self):
        return u'%s %s' % (self.nombre, self.apellido)

class Calificacion(models.Model):
    puntaje = models.IntegerField(default=1)
    comentario = models.TextField(max_length=200,blank=True)
    pub_date = models.DateTimeField(default=datetime.now())
    profesor = models.ForeignKey(Profesor,blank=False)
    user = models.ForeignKey(User,default='')

    def __int__(self):           
        return self.puntaje

class Config_pagina(models.Model):
    paginacion = models.IntegerField(default=5)
    top = models.IntegerField(default=5)
    recientes = models.IntegerField(default=5)
    populares = models.IntegerField(default=5)
    class Meta:
        verbose_name='Paginacion'
        verbose_name_plural='Configurar paginas'

    def __int__(self):           
        return self.paginacion

votacion/forms.py
#encoding:utf-8 
from django.forms import ModelForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from .models import Profesor,Calificacion
from django.utils.translation import ugettext_lazy as _

#class ContactoForm(forms.Form):
#	correo = forms.EmailField(label='Tu correo electrónico')
#	mensaje = forms.CharField(widget=forms.Textarea)

class ProfesorForm(ModelForm):

    class Meta:
        model = Profesor
        fields = ['apellido','nombre','apodo','universidad', 'unidad','foto', 'linkedin']

class CalificacionForm(ModelForm):
    def __init__(self,*args,**kwargs):
        super (CalificacionForm,self ).__init__(*args,**kwargs) # populates the post
        self.fields['profesor'].queryset = Profesor.objects.filter(confirmado_flag=1)
  
    class Meta:
        model = Calificacion
        fields = ['profesor', 'comentario','puntaje']

 
class LoginForm(AuthenticationForm):
    username = forms.RegexField(regex=r'^\w+$', widget=forms.TextInput(
        attrs={'maxlength': 30, 'class': 'form-control', 'placeholder': _("Username")}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'maxlength': 30, 'class': 'form-control', 'placeholder': _("Password")}))

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        if self.errors:
            for f_name in self.fields:
                classes = self.fields[f_name].widget.attrs.get('class', '')
                classes += ' has-error'
                self.fields[f_name].widget.attrs['class'] = classes


class RegistracionForm(forms.Form):
    first_name = forms.RegexField(regex=r'^\w+$', widget=forms.TextInput(
        attrs={'maxlength': 30, 'class': 'form-control','placeholder': _("Nombre")}))
    last_name = forms.RegexField(regex=r'^\w+$', widget=forms.TextInput(
        attrs={'maxlength': 30, 'class': 'form-control', 'placeholder': _("Apellido")}))
    email = forms.EmailField(widget=forms.TextInput(
        attrs={'maxlength': 60, 'class': 'form-control', 'placeholder': _("Email Address")}))
    username = forms.RegexField(regex=r'^\w+$', widget=forms.TextInput(
        attrs={'maxlength': 30, 'class': 'form-control', 'placeholder': _("Username")}))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={'maxlength': 30, 'class': 'form-control', 'placeholder': _("Password")}))
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={'maxlength': 30, 'class': 'form-control', 'placeholder': _("Confirm your password")}))

    def __init__(self, *args, **kwargs):
        super(RegistracionForm, self).__init__(*args, **kwargs)
        if self.errors:
            for f_name in self.fields:
                if f_name in self.errors:
                    classes = self.fields[f_name].widget.attrs.get('class', '')
                    classes += ' has-error'
                    self.fields[f_name].widget.attrs['class'] = classes

    def clean_username(self):
        try:
            user = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_("La Cuenta ya existe."))

    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("La password es diferente."))
        return self.cleaned_data

votacion/views.py
from django.shortcuts import get_object_or_404, render_to_response
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django.template import RequestContext
from .forms import ProfesorForm,CalificacionForm,RegistracionForm,LoginForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User,AnonymousUser
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.views.generic.edit import FormView
from django.views.generic import TemplateView
from django.views.generic.base import View
from .models import Profesor,Calificacion,Config_pagina
from django.db.models import Count,Sum
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
class IndexView(TemplateView):

    def dispatch(self, request, *args, **kwargs):
        return render_to_response('votacion/index.html',{'user':request.user})

class LoginView(FormView):
    template_name = 'registration/login.html'
    form_class = LoginForm

    @method_decorator(csrf_protect)
    def dispatch(self, *args, **kwargs):
        return super(LoginView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super(LoginView, self).form_valid(form)

    def get_success_url(self):
        try:
            return '/votacion'
        except:
            return "/accounts/profile"


class LogoutView(View):

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LogoutView, self).dispatch(*args, **kwargs)

    def get(self, request):
        logout(request)
        return HttpResponseRedirect('/votacion')


class RegistrarView(FormView):
    template_name = 'registration/register.html'
    form_class = RegistracionForm

    @method_decorator(csrf_protect)
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect('/votacion')
        else:
            return super(RegistrarView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = User.objects.create_user(
            first_name=form.cleaned_data['first_name'],
            last_name=form.cleaned_data['last_name'],
            email=form.cleaned_data['email'],
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password1']
        )
        return super(RegistrarView, self).form_valid(form)

    def get_success_url(self):
        return '/votacion/registrarme/success/'


class RegistrarSuccessView(TemplateView):
    template_name = 'registration/success.html'

def nuevo_Recomendado(request):
    if request.method=='POST':
        formulario = ProfesorForm(request.POST,request.FILES)
        if formulario.is_valid():
            profesor=formulario.save(commit=False)
            profesor.user = request.user
            profesor.save()
            return HttpResponseRedirect('/votacion/recomendar/success')
    else:
        formulario = ProfesorForm()
        #se usa para filtrar que mostramos formulario.fields["universidad"].queryset = Universidad.objects.filter(nombre='UAI')
        return render_to_response('votacion/recomendarform.html',{'formulario':formulario}, context_instance=RequestContext(request))

def recomendarSuccess(request):
    return render_to_response('votacion/recomendacion-success.html',{'user':request.user})
    

def nueva_Calificacion(request):
    if request.method=='POST':
        formulario = CalificacionForm(request.POST)
        if formulario.is_valid():
            calificacion = formulario.save(commit=False)
            calificacion.user = request.user
            calificacion.save()
            return HttpResponseRedirect('/votacion/calificar')
    else:
 
        formulario = CalificacionForm()
        return render_to_response('votacion/calificacionform.html',{'formulario':formulario}, context_instance=RequestContext(request))


def RecientesProfesoresView(request):
    per_page=Config_pagina.objects.values_list('recientes', flat=True)
    p=Calificacion.objects.select_related('profesor').order_by('-pub_date')[:per_page[0]]

    return render_to_response('votacion/recientes.html',{'profesores':p,'user':request.user})

def PopularesProfesoresView(request):
    per_page=Config_pagina.objects.values_list('populares', flat=True)
    p=Calificacion.objects.select_related('profesor').order_by('-puntaje')[:per_page[0]]

    return render_to_response('votacion/populares.html',{'profesores':p,'user':request.user})


def TopXProfesoresView(request):
    tabla = Profesor.objects.annotate(algo=Sum('calificacion__puntaje')).filter(confirmado_flag=1,calificacion__puntaje__gte=0).order_by('-algo')
    per_page=Config_pagina.objects.values_list('top', flat=True)
    paginator = Paginator(tabla, per_page[0]) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        profesores = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        profesores = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        profesores = paginator.page(paginator.num_pages)

    return render_to_response('votacion/top.html',{'profesores':profesores,'user':request.user})

def BuscarProfesoresView(request):
    if request.GET:
   
        search_term = request.GET.get('search_txt')
        flag = request.GET.get('busflag')
        
        #0 Si es simple o 1 si es avanzada
        if flag=='0':
            results = Profesor.objects.filter(nombre__iexact=search_term,confirmado_flag=1) | Profesor.objects.filter(apellido__iexact=search_term,confirmado_flag=1)| Profesor.objects.filter(apodo__iexact=search_term,confirmado_flag=1)
        else:
            results = Profesor.objects.filter(nombre__iexact=search_term,confirmado_flag=1) | Profesor.objects.filter(apellido__iexact=search_term,confirmado_flag=1)| Profesor.objects.filter(apodo__iexact=search_term,confirmado_flag=1)| Profesor.objects.filter(unidad__nombre__iexact=search_term,confirmado_flag=1)| Profesor.objects.filter(universidad__nombre__iexact=search_term,confirmado_flag=1)
        
        per_page=Config_pagina.objects.values_list('paginacion', flat=True)
        paginator = Paginator(results, per_page[0]) # Show 25 contacts per page

        page = request.GET.get('page')
        try:
            profesores = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            profesores = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            profesores = paginator.page(paginator.num_pages)

        return render_to_response('votacion/busca.html', {'profesores': profesores, 'user':request.user,'search_txt':search_term,'flag':flag})
    else:
        return render_to_response('votacion/busca.html',{'user':request.user})

votacion/templates/votacion/aside.html
<aside>
    <div class="col-md-3 hidden-xs hidden-sm">
        <div class="sidebar-module sidebar-module-inset">
  			  <h3>¿Tenes algun profesor para recomendar??</h3>
    			<div class="panel-footer"><a href="{% url 'votacion:recomendar' %}" class="btn btn-success btn-block btn-lg">Tu opinion vale!</a>
          </div>
        </div>
        <div class="panel panel-primary">
      			<div class="panel-heading">
        		<h3 class="panel-title">Profesores recientes</h3>
      			</div>
      			<div class="panel-body">
        			Sin actividad!
      			</div>
      			<div class="panel-footer sidebar-footer">
      				<a href="">ver todo</a>
      			</div>
		    </div>
    		<div class="panel panel-success">
      			<div class="panel-heading">
        		    <h3 class="panel-title">Profesores top X</h3>
      			</div>
      			<div class="panel-body">
        			Sin actividad!
      			</div>
            <div class="panel-footer sidebar-footer">
              <a href="">ver todo</a>
            </div>
    		</div>
    		<div class="panel panel-default">
      			<div class="panel-heading">
        		<h3 class="panel-title">Profesores mas populares</h3>
      			</div>
      			<div class="panel-body">
        			Sin actividad!
      			</div>
            <div class="panel-footer sidebar-footer">
              <a href="">ver todo</a>
            </div>
    		</div>
    </div>    
</aside>

votacion/templates/votacion/base.html
<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="UTF-8">
		<title>{% block titulo %}{% endblock %}</title>
		<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
		<link rel="stylesheet"  href="{{STATIC_URL}}/static/css/bootstrap.min.css" rel="stylesheet">
		<link rel="stylesheet"  href="{{STATIC_URL}}/static/css/bootstrap-theme.min.css" rel="stylesheet">
		<link rel="stylesheet"  href="{{STATIC_URL}}/static/css/estilos.css" rel="stylesheet">
		<link rel="stylesheet" href="{{STATIC_URL}}/static/css/star-rating.css" media="all" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="{{STATIC_URL}}/static/js/mine.js"></script>
		<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}/static/css/style.css" />
	</head>
	<body>
		<header>
			{% include 'votacion/navbar.html' %}
		</header>
		<section class="jumbotron">
			{% block contenido %}{% endblock %}
		</section>
		
		{% include 'votacion/footer.html' %}

    	<!-- ARCHIVOS JAVASCRIPTS-->

    	{% block script %}{% endblock %}

    	<script src="{{STATIC_URL}}/static/js/star-rating.js" type="text/javascript"></script>
    	<script src="{{STATIC_URL}}/static/js/jquery.min.js"></script>
    	<script type="text/javascript" src="{{STATIC_URL}}/static/js/bootstrap.min.js"></script>
    	<script>
    		$("#id_universidad").attr('required', 'required');
    		$("#id_unidad").attr('required', 'required');
    	</script>
	</body>
</html>

votacion/templates/votacion/busca.html
{% extends 'votacion/base.html' %}
{% block titulo %}Pagina de busquedas{% endblock %}

{% block contenido %}
<div class="container recientes">
	<div class="page-header">
		<h1>Busqueda de profesores</h1>
	</div>
	<div class="row busqueda">
		<h3>Formulario de Busqueda</h3>
		<hr>
		<form method="GET" id="simple" action="" class="form-inline">
			<div>
				<div>Buscar Profesores:</div>
			    	<div id="custom-search-input">
			    		<div class="input-group col-md-4">
				            <input type="text" class="form-control input-md" placeholder="Buscar..." name="search_txt" />

				        </div>
		            </div>
		    </div>
			    <br>
				<div>
				    <div class="btn-group" data-toggle="buttons" >
				    	<h5>* Seleccione Simple para buscar por: Nombre, Apellido, Apodo</h5>
				    	<h5>* Seleccione Advance para buscar por: Nombre, Apellido, Apodo, Universidad, Unidad</h5>
				    	<br>
		                <label class="btn btn-default active" >
		                    <input type="radio" id="q156" name="busflag" value="0"  checked/>Busqueda Simple
		                </label> 
		                <label class="btn btn-default">
		                    <input type="radio" id="q157" name="busflag" value="1" />Busqueda Advance
		                </label> 
		            </div>
				</div><br>
				<div>
			    	<input type="submit" class="btn btn-primary" value="Buscar"></input>
			    </div>
			</div>
		</form>
		<hr>
		<h3>Resultados</h3>
		<hr>
		<div class="table-responsive"> 
			<table  class="table">
				<thead>
				    <tr>
				        <th>Foto</th>
				        <th>Profesor</th>
				        <th>Apodo</th>
				        <th>Universidad</th>
				        <th>Unidad</th>
				    </tr>
			    </thead>
			    <tbody>
				    
				    {% for item in profesores %}
				    <tr> 
				        <td><img src="/media/{{ item.foto }}" style="with:50px;height:50px" /></td>
						<td>{{ item.nombre }} {{ item.apellido }}</td>
						<td>{{ item.apodo }}</td>
						<td>{{ item.universidad.nombre }}</td>
						<td>{{ item.unidad.nombre }}</td>
					</tr>
				    {% endfor %}
				    
				</tbody>
			</table>
		</div>
			<div class="pagination">
			    <span class="step-links">
			        {% if profesores.has_previous %}
			            <a href="?page={{ profesores.previous_page_number }}&search_txt={{search_txt}}&busflag={{flag}}">previous</a>
			        {% endif %}

			        <span class="current">
			            Page {{ profesores.number }} of {{ profesores.paginator.num_pages }}.
			        </span>

			        {% if profesores.has_next %}
			            <a href="?page={{ profesores.next_page_number }}&search_txt={{search_txt}}&busflag={{flag}}">next</a>
			        {% endif %}
			    </span>
			</div>
	</div>
</div>


{% endblock %}

votacion/templates/votacion/calificacionform.html
{% extends 'votacion/base.html' %}
{% block titulo %}Calificacion{% endblock %}
{% block encabezado %}Califica a tu Profesor{% endblock %}
{% block contenido %}
<div class="container profesor">
    <div class="row">
        <div class="page-header">
            <h1>Formulario de Recomendacion</h1>
        </div>
		<form role="form" id='formulario' method='POST' action=''>{% csrf_token %}
			<div class="form-group">
				<p><label for="profesor" class="control-label ">Profesor</label></p>
	            <p>{{formulario.profesor}}</p>
	            <p><label for="comentario" class="control-label ">Comentario</label></p>
	            <p>{{formulario.comentario}}</p>
				<label>Califica de 1 a 5 estrellas: </label>
				<p class="clasificacion">
				    <input id="radio1" type="radio" name="puntaje" value="5">
				    <label for="radio1" class="estrella">★</label>
				    <input id="radio2" type="radio" name="puntaje" value="4">
				    <label for="radio2" class="estrella">★</label>
				    <input id="radio3" type="radio" name="puntaje" value="3">
				    <label for="radio3" class="estrella">★</label>			    
				    <input id="radio4" type="radio" name="puntaje" value="2">
				    <label for="radio4" class="estrella">★</label>			    
				    <input id="radio5" type="radio" name="puntaje" value="1">
				    <label for="radio5" class="estrella">★</label>
				</p>
			</div>
			<div class="col-xs-5"></div>
			<button type="submit" class="btn btn-primary" value='Enviar'>Enviar</button>
		</form>
	</div>
</div>
{% endblock %}

votacion/templates/votacion/footer.html
<footer class="footer">
	<h3>Sistema de recomendacion para la universidad de Ezeiza</h3>
	<h4>Tecnicas de Programacion</h4>
	<p>Alumnos: Rodriguez Carlos</p>
	<p>Fernandez Sergio</p>
</footer>

votacion/templates/votacion/index.html
{% extends 'votacion/base.html' %}
{% block titulo %}Recomendar Profesores{% endblock %}
{% block encabezado %}Bienvenido{% endblock %}
{% block contenido %}

<div class="container">
	<div class="page-header">
		<h1 style="text-align:center">Bienvenido</h1>
		<hr>
		<p>En esta pagina podras recomendar a Profesores de tu Universidad, para ello es necesario conocer su nombre, apellido, el apodo y foto son opcionales, una vez que nuestro administrador alla verificado los datos ingresados, recibiras un mail, de confirmacion o rechazo.</p>
		<p>Si fuera confirmado podras ingresar y calificarlo en un rago de 1 a 5, tambien podras dejar un comentario.</p>
	</div>
</div>

{% endblock %}

votacion/templates/votacion/msj_sin_resultados.html
<div class="panel panel-default">
  <div class="panel-heading">Sin resultados</div>
  <div class="panel-body">Lo sentimos, por el momento no hay resultados recientes acorde lo que buscas, te esperamos en otro momento. <br>Saludos!</div>
</div>

votacion/templates/votacion/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top ">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Menu</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'votacion:index' %}">UPE</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse pull-right" >
            <ul class="nav navbar-nav">
                <li><a href="{% url 'votacion:index' %}">Inicio</a></li>
            
                <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">    Listados<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'votacion:recientes' %}">Recientes</a></li>
                                <li><a href="{% url 'votacion:populares' %}">Populares</a></li>
                                <li><a href="{% url 'votacion:top' %}">Top X</a></li>
                                <li><a href="{% url 'votacion:busca' %}">Buscar</a></li>
                            </ul>
                </li>
                {% if user.is_authenticated %}
                <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">    Acciones<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'votacion:recomendar' %}">Recomendar</a></li>
                                <li><a href="{% url 'votacion:calificar' %}">Votar</a></li>
                            </ul>
                </li>
                {%endif%}
            </ul>
            <!--<div class="container">
            <form action="#" class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Buscar">   
                </div>
                <button type="submit" class="btn btn-primary">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </form>-->
            {% if user.is_authenticated %}
                <div class="btn-group navbar-btn navbar-right">
                    <button type="button" class="btn btn-success">
                         <span class="glyphicon glyphicon-user"></span>  {{ user.username }}
                    </button>
                    <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    	<span class="caret"></span>
                    	<span class="sr-only">Toggle Dropdown</span>
                    </button>
				    <ul class="dropdown-menu">
				    	<!--<li><a href="#">Perfil</a></li>
				    	<li><a href="#">Cuenta</a></li>-->
					    {% if user.is_superuser %}
					        <li><a href="/admin">Administrar sitio</a></li>
						{% endif%}
				    	<li role="separator" class="divider"></li>
				    	<li><a href="{% url 'votacion:logout' %}">Salir</a></li>
				  	</ul>
                </div>
            {% else %}
                <form action="#" class="form-inline navbar-form navbar-right">
                    <a href="{% url 'votacion:login' %}" class="btn btn-default" role="button">
                        <span class="glyphicon glyphicon-user"></span> Ingresar
                    </a>
                    <a href="{% url 'votacion:registrarme' %}" class="btn btn-success" role="button">
                        <span class="glyphicon glyphicon-pencil"></span>  Registrate
                    </a>
                </form>
            {% endif %}
            
            </div><!--/.nav-collapse -->
    </div>
</nav>

votacion/templates/votacion/paginacion_listados.html
	<div class="pagination">
	    <span class="step-links">
	        {% if profesores.has_previous %}
	            <a href="?page={{ profesores.previous_page_number }}">previous</a>
	        {% endif %}

	        <span class="current">
	            Page {{ profesores.number }} of {{ profesores.paginator.num_pages }}.
	        </span>

	        {% if profesores.has_next %}
	            <a href="?page={{ profesores.next_page_number }}">next</a>
	        {% endif %}
	    </span>
	</div>

votacion/templates/votacion/recomendacion-success.html
{% extends 'votacion/base.html' %}

{% block contenido %}
<div class="container profesor">
    <div class="row">
        <div class="page-header">
            <h1>Exito al enviar!!</h1>
        </div>
        <div class="panel panel-success">
        	<p style="color:black; padding-left:30px;padding-top:5px;">
        		Tu recomendacion ah sido aceptada, se te enviara un email cuando el administrador confirme/rechaze tu recomendacion. <br><br>
        		Muchas gracias, un Saludo!
        	</p>
        </div>
    </div>
</div>
{% endblock %}